Run consumer in docker

diff --git a/msg-consumer/Dockerfile b/msg-consumer/Dockerfile
--- a/msg-consumer/Dockerfile
+++ b/msg-consumer/Dockerfile
@@ -1,11 +1,11 @@
 FROM openjdk:11-slim-buster
 
-ENV PROXY_ADDRESS 192.168.6.145:80
+# ENV PROXY_ADDRESS 192.168.6.145:80
 
-ENV HTTP_PROXY http://$PROXY_ADDRESS/
-ENV http_proxy http://$PROXY_ADDRESS/
-ENV HTTPS_PROXY http://$PROXY_ADDRESS/
-ENV https_proxy http://$PROXY_ADDRESS/
+# ENV HTTP_PROXY http://$PROXY_ADDRESS/
+# ENV http_proxy http://$PROXY_ADDRESS/
+# ENV HTTPS_PROXY http://$PROXY_ADDRESS/
+# ENV https_proxy http://$PROXY_ADDRESS/
 
 RUN apt-get update && apt-get install -yq \
        dnsutils \
@@ -31,9 +31,10 @@ ENV https_proxy ""
 ENV LD_PRELOAD "/usr/lib/x86_64-linux-gnu/libjemalloc.so.2"
 
 ARG JAR_FILE
-ADD ${JAR_FILE} app.jar
+RUN echo ${JAR_FILE}
+ADD ${JAR_FILE} /app.jar
 EXPOSE 8080
 
-CMD ["java -jar /app.jar"]
-#HEALTHCHECK --interval=10s --timeout=8s --start-period=120s --retries=3 CMD curl --fail http://localhost:8080/actuator/health/ || exit 1
+CMD ["java", "-jar", "/app.jar"]
+# HEALTHCHECK --interval=10s --timeout=8s --start-period=120s --retries=3 CMD curl --fail http://localhost:8080/actuator/health/ || exit 1
 
